### ISSUE TITLE
people.opml is both ignored and under revision control?

### ISSUE THREAD

**Issue by samwilson** [mauricesvay/moonmoon#69]
The `people.opml` file is listed in `.gitignore`, but it's also included in the repository. Is this intentional? I've just switched to running _moonmoon_ from a Git clone, and it's clobbering this file when I update!

**Comment by samwilson** [comment]
Also, should `admin/inc/pwd.inc.php` also be ignored?

**Comment by mauricesvay** [comment]
Yes, they should probably be ignored

**Comment by nashe** [comment]
Theses commits were merged, I assume that this issue can be closed now.
