### ISSUE TITLE
Deprecated: Assigning the return value of new by reference is deprecated

### ISSUE THREAD

**Issue by GaneshKandu** [mauricesvay/moonmoon#78]
Hi, I am getting Error in moonmoon v.8.12
php version 5.4.45

**Deprecated**: Assigning the return value of new by reference is deprecated in **{{path}}/app/lib/simplepie/simplepie.inc** on line **716**

**Deprecated**: Assigning the return value of new by reference is deprecated in **{{path}}/app/lib/simplepie/simplepie.inc** on line **1083**

**Deprecated**: Assigning the return value of new by reference is deprecated in **{{path}}/app/lib/simplepie/simplepie.inc** on line **1591**

**Deprecated**: Assigning the return value of new by reference is deprecated in **{{path}}/app/lib/simplepie/simplepie.inc** on line **1632**

**Deprecated**: Assigning the return value of new by reference is deprecated in **{{path}}/app/lib/simplepie/simplepie.inc** on line **1652**

**.**

**.**

**.**

**Comment by nashe** [comment]
The SimplePie library is no more inside the `app/lib/` folder, since it was a very old version. It's now fetched using `composer` (see the readme for more information about it) and put inside `vendors/`.

You have three options:
- Upgrade to the last version of moonmoon. You'll need to be able to use `composer`,
- Download the last version of [SimplePie](http://simplepie.org/) and replace the file `simplepie.inc` by the new one,
- Remove the `&` sign (`=&` becomes `=`).

Keep me in touch about what you tried and what are the results ;-)

**Comment by GaneshKandu** [comment]
" Remove the & sign (=& becomes =) " 
thanks its working for me

I Have just installed moonmoon latest version v.8.12, so i cant upgrade if its not your latest version
what is the last version of moonmoon.??

**Comment by nashe** [comment]
You are right, I forgot that the website is linking to the last stable version and not the dev one. If Simple Pie works this way, keep the v8.12 :-)

**Comment by GaneshKandu** [comment]
but i am still getting errors



**Strict Standards**:  Non-static method Spyc::YAMLLoad() should not be called statically in **{{path}}admin/index.php** on line **8**



**Strict Standards**:  Non-static method OpmlManager::load() should not be called statically, assuming $this from incompatible context in **{{path}}app/classes/Planet.class.php** on line **237**



**Strict Standards**:  Non-static method SimplePie_Misc::is_subclass_of() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **1100**



**Strict Standards**:  Non-static method SimplePie_Misc::fix_protocol() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **809**



**Strict Standards**:  Non-static method SimplePie_Misc::normalize_url() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **8582**



**Strict Standards**:  Non-static method SimplePie_Misc::percent_encoding_normalization() should not be called statically in **{{path}}app/lib/simplepie/simplepie.inc** on line **8661**



**Strict Standards**:  Non-static method SimplePie_Misc::parse_url() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **8662**



**Strict Standards**:  Non-static method SimplePie_Misc::remove_dot_segments() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **8667**



**Strict Standards**:  Non-static method SimplePie_Misc::compress_parse_url() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **8669**



**Strict Standards**:  Non-static method SimplePie_Misc::parse_url() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **8583**



**Strict Standards**:  Non-static method SimplePie_Misc::parse_url() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **1532**



**Strict Standards**:  call_user_func() expects parameter 1 to be a valid callback, non-static method SimplePie_Cache::create() should not be called statically in **{{path}}app/lib/simplepie/simplepie.inc** on line **1536**



**Strict Standards**:  Non-static method SimplePie_Misc::get_curl_version() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **7609**



**Strict Standards**:  Non-static method SimplePie_Misc::get_curl_version() should not be called statically, assuming $this from incompatible context in **{{path}}app/lib/simplepie/simplepie.inc** on line **7621**



**Strict Standards**:  usort() expects parameter 2 to be a valid callback, non-static method PlanetItem::compare() should not be called statically in **{{path}}app/classes/Planet.class.php** on line **297**



**Warning**:  Cannot modify header information - headers already sent by (output started at {{path}}admin/index.php:8) in **{{path}}admin/index.php** on line **25**

**Comment by nashe** [comment]
Can you please add the `error_reporting(E_ALL & ~E_STRICT);` on L13 of `index.php`, instead of `error_reporting(E_ALL);`?

**Comment by GaneshKandu** [comment]
Ok ! 
added to index.php and admin/index.php
and its works now thanks
:+1:

**Comment by nashe** [comment]
Awesome, have a nice day!

**Comment by GaneshKandu** [comment]
:+1:
