### ISSUE TITLE
Strict Standards: Non-static method SimplePie_

### ISSUE THREAD

**Issue by silvyn** [mauricesvay/moonmoon#81]
Bonjour !

J'ai quelques erreurs PHP sur l'admin, visiblement lié à SimplePie : 

Strict Standards: Non-static method Spyc::YAMLLoad() should not be called statically in /home/user/www/moonmoon/admin/index.php on line 8

Strict Standards: Non-static method SimplePie_Misc::percent_encoding_normalization() should not be called statically in /home/user/www/moonmoon/app/lib/simplepie/simplepie.inc on line 8661

Strict Standards: call_user_func() expects parameter 1 to be a valid callback, non-static method SimplePie_Cache::create() should not be called statically in /home/user/www/moonmoon/app/lib/simplepie/simplepie.inc on line 1536

Strict Standards: usort() expects parameter 2 to be a valid callback, non-static method PlanetItem::compare() should not be called statically in /home/user/www/moonmoon/app/classes/Planet.class.php on line 297

Savez-vous comment les corriger ? C'est un hébergement mutualisé où je n'ai généralement pas de soucis particulier (j'utilise la version 8.2 téléchargé ce soir depuis le site http://moonmoon.org/)

J'ai tenté de voir avec la version disponible ici mais sans succès.

**Comment by nashe** [comment]
Aloha !

Quelle version est-ce que tu utilises ? La 8.12 provenant de moonmoon.org ? 

Si c'est le cas, tu devrais pouvoir régler ça en rajoutant `static` devant `function percent_encoding_normalization($match)`, ligne 8672.

**Comment by silvyn** [comment]
Merci @nashe,
Oui pardon il fallait lire la 8.12.
Cela corrige donc l'erreur de la ligne 8672, merci :)

Reste celle de la ligne 1536, qui s'affiche comme la précédente autant de fois qu'il y a de flux. Une idée ?

Pour les deux autres c'est moins gênant.

**Comment by mauricesvay** [comment]
N'hésitez pas à ouvrir un PR si vous avez un fix :)

**Comment by nashe** [comment]
Oops, j'ai vu ton message avant que tu ne l'aies édité, je regarde ça dès que possible. Mais tout devrait être réglé en indiquant `static` devant la définition des fonctions qui posent le soucis (`YAMLLoad()`, `create()` de `SimplePie_Cache`, `compare()` de `PlanetItem`).

Ce souris n'est pas normalement plus présent avec une version plus récente de SimplePie (telle que celle téléchargée par `composer`), tu peux aussi juste remplacer le fichier avec une version plus récente de la librairie.

**Comment by nashe** [comment]
Étant donné qu'il s'agit d'un problème lié à SimplePie et que c'est réglé sur `master`, je pense que cette issue peut être fermée ?

cc @mauricesvay @silvyn

**Comment by mauricesvay** [comment]
J'essaierai de regarder pour corriger ça dans les jours qui viennent.

**Comment by silvyn** [comment]
En effet, l'installation via la branche master et composer ne comporte pas ces messages d'erreurs. Me voilà avec une installation fonctionnelle 👍
