### ISSUE TITLE
PHP7 ?

### ISSUE THREAD

**Issue by silvyn** [mauricesvay/moonmoon#82]
Hello,
Avez-vous prévu de travailler sur PHP7 ? Sauf erreur cela ne semble pas fonctionner. Je viens de migrer et pour le reste, pas de soucis, il me reste plus qu'à trouver une solution pour un planet PHP7.

**Comment by nashe** [comment]
Aloha, est-ce que tu as encore sous la main les erreurs que tu as eues ? Ça fait un moment que je n'y ai pas touché mais je me rappelle avoir travaillé sur le projet avec PHP 7.x sans avoir rencontré de soucis particulier. Je peux sûrement faire quelques PR sur ce sujet dans le week-end si besoin :-)

**Comment by mauricesvay** [comment]
Je n'ai pas de projet immédiat pour passer en PHP7, mais c'est peut être des erreurs qui peuvent se corriger facilement.

**Comment by silvyn** [comment]
Bonsoir @nashe 
Bon honnêtement c'est sans doute pas uniquement que PHP7, cf mon précédent ticket, SimplePie ne doit pas m'aimer.
Pour l'instant côté public j'ai maintenant une page blanche.
Côté admin, après authentification, j'ai ce message : 
Parse error: syntax error, unexpected 'new' (T_NEW) in /home/monlogin/www/moonmoon/app/lib/simplepie/simplepie.inc on line 716

**Comment by nashe** [comment]
Yep, il faut que tu retires toutes les occurrences de `=&`, syntaxe qui n'est désormais plus valide (cf. #78).

Une solution peut-être plus simple consisterait peut-être à ce que tu utilises la version issue de la branche `master`, où je peux te garantir que tout sera fonctionnel (et je m'engage à m'occuper des soucis si il y en a ;-))

**Comment by silvyn** [comment]
Et bien je viens bien de l'aide alors ;)
J'ai téléchargé une copie de la branche master, version dev donc.
Mais si je vais sur install.php j'ai une page blanche..

**Comment by nashe** [comment]
Est-ce que tu as lancé `composer install` afin de télécharger les dépendances ? Si non, la page blanche est normale (cf. #79). 
Je vais faire une PR pour ajouter le dossier `vendor/` au dépôt afin que les personnes n'ayant pas d'accès à un shell sur leur machine d'hébergement aient moins de soucis à installer la version `dev`.

**Comment by silvyn** [comment]
C'est le problème, même si j'ai un accès ssh, je n'ai pas `composer` sur mon hébergement mutualisé, j'ai justement regardé hier si je pouvais. Je regarde vers ton fork pour voir. Merci.

**Comment by nashe** [comment]
À partir du moment où tu as un accès SSH, `composer` peut être installé sur ton hébergement [en suivant les commandes données sur son site](https://getcomposer.org/download/). Tu n'as pas besoin d'avoir de privilèges particuliers, l'installation sera propre à ton utilisateur.

**Comment by silvyn** [comment]
Alors avec l'ajout du dossier `vendor,` j'ai pu suivre l'assistant d'installation, m'authentifier, et voir l'interface d'admin. Au premier ajout de flux, page blanche..
Bon je vais tenter alors d'installer `composer` pour voir si ça me permet d'aller plus.

**Comment by nashe** [comment]
[Tu peux ajouter `?debug` dans l'URL afin d'obtenir un peu plus d'information sur l'origine des erreurs.](https://github.com/mauricesvay/moonmoon/blob/master/app/app.php#L4)

**Comment by silvyn** [comment]
Comme ceci par exemple ? /`index.php?debug` Toujours page blanche.

**Comment by silvyn** [comment]
Alors, je me suis un peu plus familiarisé avec composer pour l'installation.
J'ai réessayé avec la branche master d'ici, et ensuite `php composer.phar install `. Cette fois-ci j'ai bien eu une série de téléchargement et d'installation (Package operations: 34 installs, 0 updates, 0 removals).
Puis je finalise l'installation via install.php. Pour l'instant tout vas bien. La page public sans item est opérationnelle. Je m'authentifie, j'ajoute un flux atom.. et ouf je n'ai pas une page blanche ! Toujours la page d'admin \o/
Donc aucun soucis avec PHP7, on va pouvoir clôturer ce fil :)

**Comment by nashe** [comment]
À la vue du code que j'ai indiqué, il faut mettre `?debug=quelquechose` pour que ça soit effectif ;-)

Je vais essayer de proposer quelque chose de propre pour éviter que tout le monde aie à `composer install` (ça n'est pas toujours possible, trop compliqué, etc.). Travis était censé créer une _release_ intégrant le dossier `vendors` à chaque nouveau commit, ce qui évite de polluer le dépôt, [mais ça n'a jamais été définitivement mis en place](https://github.com/mauricesvay/moonmoon/blob/master/.travis.yml#L21).

**Comment by silvyn** [comment]
Donc **moonmoon** fonctionne très bien avec PHP7 👍 
Je clôture ce fil, encore merci @nashe pour ton aide et les pistes. J'ai écris un rapide billet billet sur mon blog pour info.

**Comment by mauricesvay** [comment]
Merci @nashe pour l'aide! 
Je viens de publier une nouvelle version issue de `master`. J'en profite pour changer le système  de versions pour utiliser semver.

Les archives de l'application seront désormais disponible sur la page de releases github.

https://github.com/mauricesvay/moonmoon/releases

**Comment by silvyn** [comment]
Pour info @mauricesvay j'ai testé rapidement l'archive, et ne constate pas d'anomalie :)
Peut-être faire le ménage avec le dossiers tests ?

**Comment by nashe** [comment]
_Mea culpa_, c'est vrai que j'ai visé un peu large et qu'il y a beaucoup de fichiers qui ne sont pas utilisés (test d'intégration, etc.), je pensais en écrire mais je ne l'ai jamais fait. Il peut sûrement être exclu de l'archive de _release_ sans que ça soit trop handicapant.
