### ISSUE TITLE
An error in custom > views > default > top.tpl.php ??

### ISSUE THREAD

**Issue by Emmafrs** [mauricesvay/moonmoon#87]
Hello, 
I'm french and not very good in technologic langage but i use moonmoon and i like it. 

I'm actually testing the new formul (9.0.0.rc) and i think there is maybe a bug in the top.tpl.php file. 
1/ there is missing a ";" i think, no ?
2/ the url is wrong when we click on it : there is twice the same url and i think it's maybe a bug. I delete the "<?php //echo $PlanetConfig->getUrl(); ?>" part to put "./index.php" instead, but still, why the "getUrl" doesn't give us the real url ? 

Can someone explain it to me please ? Have you the same issue ?

**Comment by nashe** [comment]
Hi @Emmafrs, thanks for your report!

The `;` symbol is not mandatory in this case, but I'll make a commit to add it and be consistent in the coding style. You can also create a _Pull Request_ to add it, if you want to, any contribution is appreciated ;-)

I'll take a look at your second point this evening. Please note that users encountered issues with the last version of moonmoon (see #83 #85) and I did not took time to investigate enough on it, you may encounter it as well.

**Comment by Emmafrs** [comment]
Hello nashe, 
you are french, i am french, and so we speak in english. Lol. 

Thanks for the fisrt explanation (the ; symbol is not mandatory). 
I let you take a look for the second point. 

I had the same issue with the last version of moonmoon than other users (the people;opml file empty), i wrote it on the  #83. 

I can't create a Pull Request, i just arrive this morning on github, i don't really understand how all this is working and i don't always have the right terms to explain my issues (even in french, i code by intuition the most part of time, that's not my job). 

Thanks for your reply :)

**Comment by nashe** [comment]
I saw your message on #83, I'll try to find some time to work on it again.

We can switch back to French if you think that it'll be easier for you to explain what are your issues! 

If you wish to try to create one PR, [there is a tutorial to discover how to work on Github](https://try.github.io/levels/1/challenges/1) and [their help pages](https://help.github.com/articles/creating-a-pull-request/). If you don't, no worries, I'll do it :-)

**Comment by Emmafrs** [comment]
I tried something to understand why, that's not orthodox, but maybe it will help you to find a solution. 

First my website is on OVH. I can give you more details if you want, if the bug is only for me. 

So, i changes the "top.tpl.php" code here : 
`<div id="header">
            <h1 id="top"><a href="<?php echo $PlanetConfig->getUrl() ?>"><?php echo $PlanetConfig->getName(); ?></a></h1>
        </div>` (wich give to me http://www.example.com/http://www.example.com/ instead of simply http://www.example.com/)

by this unorthodoxe code : 
`<div id="header">
            <h1 id="top"><a href="<?php echo $PlanetConfig->getName() ?>"><?php echo $PlanetConfig->getName(); ?></a></h1>
        </div>` (yes, 2 getName but the result is http://www.example.com/My Moonmoon Name !! It's weird, but maybe it will help you to find from where the problem is)

**Comment by nashe** [comment]
Can you try to remove the `cache/` folder? Just in case. You can also purge the cache from the administration area.

**Comment by Emmafrs** [comment]
I do it slowly and progressively, i think the problem is in the install.php file, cause that's where the config.yml file is created and that's in this file there are the url and the name. 
I compare my config.yml file with this last version of moonmoon and an older version, and the url is not write properly on this last version.

**Comment by Emmafrs** [comment]
Ah je n'avais pas lu tes derniers messages. Donc je switche un peu en français. J'ai créé un tout nouveau moonmoon specialement pour tester ce problème aujourd'hui.
Je l'ai toujours (l'url en double quand on clique sur le titre du MoonMoon en haut de la page). 

Je n'ai pas mis de flux, donc rien en cache. 

Là je regarde dans le fichier install.php, pour l'instant je ne vois rien. Mais si je compare mes 2 fichiers config.yml, celui avec moonmoon8.12 et celui avec moonmoon9.0.0, j'ai une différence au niveau de l'url : 

- dans la version 8.12, j'ai 
_---
url: http://www.example.com/_

- dans la version 9.0.0, j'ai : 
_---
url: >
    http%3A%2F%2Fwww.example.com%2F_

Les autres lignes sont correctes, et oui, j'ai bien ces signes à la place des ":" et "/". C'est pour ça que je pense que le problème se pose au moment de la création de ce fichier config.yml. Ceci dit ça n'explique toujours pas pourquoi l'url se trouve en double. To be continued...

**Comment by nashe** [comment]
Je teste tout ça dans la soirée avec les deux versions et je te tiens au courant.

**Comment by Emmafrs** [comment]
J'ai "bidouillé" en attendant. En fait le problème ne vient pas nécessairement du fichier install.php (même si il y a un problème dans la création de l'url dans le dossier config.yml, ça c'est réel). 

Mais j'ai repensé à ce que je disais plus haut quand j'avais changé le code de top.tpl.ph en 
<div id="header"> 
<h1 id="top"><a href="<?php echo $PlanetConfig->getName() ?>"><?php echo $PlanetConfig->getName(); ?></a></h1> 
</div> 

et que j'avais obtenu comme lien dans ma page principale, en cliquant sur le titre : 
 "http://www.example.com/MyMoonmoonName"

Du coup, alors que dans ce top.tpl.php modifié je ne demande pas d'url, il me la colle quand même d'office ! 

Donc j'ai changé le code en : 
<div id="header"> 
<h1 id="top"><a href=""><?php echo $PlanetConfig->getName(); ?></a></h1> 
</div> 

J'ai effacé le code (qui donnait une seconde fois l'url en fait) tout simplement, et ça marche. Je ne sais pas d'où vient le code de l'url, mais j'ai bien "http://www.example.com/" comme résultat de lien quand je clique sur le titre.

**Comment by Emmafrs** [comment]
Bon, désolée mais je teste toujours des trucs, et en fait le problème ne vient pas que du top.tpl.php. 
Dès qu'on met une ligne de code avec `href=""` , et bien on a l'url du site, dans le top.tpl.php, dans le footer, dans le sidebar et même dans l'index.tpl.php. 

Je ne sais pas comment cela se fait, mais le probleme vient de la simple écriture `href=""` (et je viens de vider le cache pour re-vérifier avant de poster ça).

**Comment by nashe** [comment]
> (même si il y a un problème dans la création de l'url dans le dossier config.yml, ça c'est réel).

L'adresse est juste encodée pour éviter de « casser » la syntaxe du fichier de configuration. Ça n'est pas correctement fait (on l'encode comme si c'était du HTML alors que le fichier de configuration est au format YML)—je ne pense pas que le problème vienne de là.

Premier point qui m'intrigue : appeler deux fois de suite `$PlanetConfig->getName()` ne devrait absolument pas retourner deux fois de suite des résultats différents, que l'on doit dans un `href` ou non, je vais déjà essayer de reproduire ce problème.

**Comment by Emmafrs** [comment]
Je viens d'éditer le passage d'avant, c'est bien un problème de création de ce fichier config.yml (je pense, comme tu peux constater je ne suis pas spécialiste du tout) ;)

**Comment by Emmafrs** [comment]
Oki, c'est bon, j'ai enlevé le filtre de l'url dans install.php. J'ai remis tous les autres fichiers d'origine. Et tout marche nickel ! Merci :)

Au lieu d'avoir : 
```
    $config = array(
        'url'           => filter_var($_REQUEST['url'],   FILTER_SANITIZE_ENCODED),
        'name'          => filter_var($_REQUEST['title'], FILTER_SANITIZE_SPECIAL_CHARS),
        'locale'        => filter_var($_REQUEST['locale'], FILTER_SANITIZE_SPECIAL_CHARS),
```
etc....

J'ai mis : 
```
    $config = array(
        'url'           => $_REQUEST['url'],   
        'name'          => filter_var($_REQUEST['title'], FILTER_SANITIZE_SPECIAL_CHARS),
        'locale'        => filter_var($_REQUEST['locale'], FILTER_SANITIZE_SPECIAL_CHARS),
```
etc....

Et le problème n'est plus. L'url s'écrit correctement dans le fichier config.yml. 
Est-ce que c'est risqué d'enlever ce filtre (est-ce que ça s'appelle un filtre ?) ? Si oui par quoi je peux le remplacer ?

**Comment by nashe** [comment]
> je ne pense pas que le problème vienne de là.

J'avais totalement tort, je viens d'arriver à la même conclusion que toi ; je corrige tout ça, désolé du temps perdu sur le soucis !

**Comment by Emmafrs** [comment]
No soucy, ça m'aura fait cogiter et décortiquer, j'aime bien ça (pis je faisais d'autres trucs à coté aussi). ;)

Mais du coup j'en reviens quand même à mes questions : est-ce que c'est risqué d'enlever ce filtre (est-ce que ça s'appelle un filtre ?) pour tout le monde ? Ça merdait chez moi, mais chez toi et les autres, est-ce que ça merdait aussi ?

**Comment by nashe** [comment]
Corrigé dans 812f73a4cabd325f5bc01718fe7679dbdb58ea25, merci !

Le filtre a été [mis en place il y a cinq ans](https://github.com/mauricesvay/moonmoon/blame/3c27f3c36ca6874b4939f3b3f1b9e4b57314072f/install.php#L18) dans le but d'éviter de casser la structure du fichier de configuration à cause d'éventuels symboles dans l'URL : il permet de transformer ces symboles leur représentation sous une autre forme (pour le navigateur, `/` et `%2F`% sont équivalents). Or ça n'était pas nécessaire (la configuration n'est pas dans ce format) et on ne décodait pas ces données avant de les afficher. Ça faisait donc des liens vers `http%3A%2F%2Fexample.com%2F`, ce qui le navigateur considère comme le nom d'une page du site, ce qui créait donc des liens vers `http://example.com/http%3A%2F%2Fexample.com%2F`. pfiou !

Le projet a été oublié quelques temps, ce qui peut indiquer que personne n'ait remarqué le soucis avant. Je crois que je n'ai jamais cliqué sur le lien vers la page d'accueil (tout en haut à gauche) et je ne l'avais donc jamais remarqué…

**Comment by nashe** [comment]
Le problème ayant été résolu, je ferme l'issue. N'hésite pas à en ouvrir d'autres si tu rencontres d'autres soucis 👍

**Comment by Emmafrs** [comment]
Merci pour l'explication :)

Si j'ai des petites remarques et suggestions à faire, je les fais où ? J'ouvre un issue aussi ?

**Comment by nashe** [comment]
C'est tout à fait ça !
